version: "3.7"
services:
  relay:
    container_name: hedera-json-rpc-relay
    image: "ghcr.io/hashgraph/hedera-json-rpc-relay:0.66.0-rc1"
    restart: "unless-stopped"
    ports:
      - 7546:7546
    pull_policy: always
    tty: true
    volumes:
      - ./.env:/home/node/app/.env
    environment:
      REDIS_ENABLED: true
      REDIS_URL: "redis://redis:6379"

  relay-ws:
    container_name: hedera-json-rpc-relay-ws
    image: "ghcr.io/hashgraph/hedera-json-rpc-relay:0.66.0-rc1"
    command: start:ws
    environment:
      HEALTHCHECK_PORT: 8547
      SUBSCRIPTIONS_ENABLED: true
      REDIS_ENABLED: true
      REDIS_URL: "redis://redis:6379"
    restart: "unless-stopped"
    ports:
      - 8546:8546
      - 8547:8547
    pull_policy: always
    tty: true
    volumes:
      - ./.env:/home/node/app/.env

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:

