apiVersion: v2
appVersion: "0.26.0-SNAPSHOT"
dependencies:
  - alias: relay
    condition: relay.enabled
    name: hedera-json-rpc-relay
    repository: file://../hedera-json-rpc-relay
  - alias: ws
    condition: ws.enabled
    name: hedera-json-rpc-relay-websocket
    repository: file://../hedera-json-rpc-relay-websocket
description: Umbrella Helm chart deployment of the hashgraph/hedera-json-rpc products
home: https://github.com/hashgraph/hedera-json-rpc-relay
icon: https://camo.githubusercontent.com/cca6b767847bb8ca5c7059481ba13a5fc81c5938/68747470733a2f2f7777772e6865646572612e636f6d2f6c6f676f2d6361706974616c2d686261722d776f72646d61726b2e6a7067
keywords:
  - blockchain
  - dlt
  - hedera
  - hashgraph
  - smart
  - contracts
  - evm
  - json
  - rpc
maintainers:
  - name: Hedera Smart Contracts Team
    email: engsmartcontracts@hedera.com
name: hedera-json-rpc
sources:
  - https://github.com/hashgraph/hedera-json-rpc-relay
type: application
version: 0.26.0-SNAPSHOT