---
apiVersion: v1
kind: Secret
metadata:
  {% if name is not defined %}{% set name = app %}{% endif %}
  name: env-{{ name }}
  {% if kubeNamespace %}
  namespace: {{ kubeNamespace }}
  {% endif %}
type: Opaque
data:
{% for k, v  in secrets.items() %}
  {{ k }}: {{ v | base64encode }}{{ '\n' }}{% endfor %}