# Default values for json-rpc-relay-websocket in CI. Configured to testnet
config:
  CHAIN_ID: '0x128'
  HEDERA_NETWORK: 'testnet'
  MIRROR_NODE_URL: 'https://testnet.mirrornode.hedera.com'

image:
  registry: registry:5001
  tag: test

resources:
  limits:
    cpu: 500m
    memory: 350Mi
  requests:
    cpu: 500m
    memory: 350Mi