apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "json-rpc-relay.fullname" . }}
  labels:
    app:  {{ template "json-rpc-relay.name" . }}
    {{ include "json-rpc-relay.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "json-rpc-relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      labels:
        app:  {{ template "json-rpc-relay.name" . }}
        {{- include "json-rpc-relay.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "json-rpc-relay.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}                
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CHAIN_ID
            value: {{ .Values.config.CHAIN_ID | squote }}        
          - name: HEDERA_NETWORK
            valueFrom:
              secretKeyRef:
                name: {{ include "json-rpc-relay.fullname" . }}
                key: HEDERA_NETWORK
                optional: false
          - name: OPERATOR_ID_MAIN
            valueFrom:
              secretKeyRef:
                name: {{ include "json-rpc-relay.fullname" . }}
                key: OPERATOR_ID_MAIN
                optional: false
          - name: OPERATOR_KEY_MAIN
            valueFrom:
              secretKeyRef:
                name: {{ include "json-rpc-relay.fullname" . }}
                key: OPERATOR_KEY_MAIN
                optional: false
          - name: OPERATOR_ID_ETH_SENDRAWTRANSACTION
            valueFrom:
              secretKeyRef:
                name: {{ include "json-rpc-relay.fullname" . }}
                key: OPERATOR_ID_ETH_SENDRAWTRANSACTION
                optional: true
          - name: OPERATOR_KEY_ETH_SENDRAWTRANSACTION
            valueFrom:
              secretKeyRef:
                name: {{ include "json-rpc-relay.fullname" . }}
                key: OPERATOR_KEY_ETH_SENDRAWTRANSACTION
                optional: true
          - name: MIRROR_NODE_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "json-rpc-relay.fullname" . }}
                key: MIRROR_NODE_URL
                optional: false
          - name: LOCAL_NODE
            valueFrom:
              secretKeyRef:
                name: {{ include "json-rpc-relay.fullname" . }}
                key: LOCAL_NODE
                optional: false
          - name: SERVER_PORT
            valueFrom:
              secretKeyRef:
                name: {{ include "json-rpc-relay.fullname" . }}
                key: SERVER_PORT
                optional: false               
        ports:
          - containerPort: {{ .Values.ports.containerPort }}
            name: {{ .Values.ports.name  }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: jsonrpcrelay
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: jsonrpcrelay                      
        resources: 
          {{- toYaml .Values.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      